### ISSUE TITLE
Is there a link to the full training dataset?

### ISSUE THREAD

**Issue by zjysteven** [johanna-rock/imRICnn#3]
Hi,

Thanks for making the code public. As discussed in issue #1, currently you only provide part of the data due to its large size. I'm wondering if there is a link to the full training dataset now?

Thanks,
Steven

**Comment by ahmedaelsharkawy** [comment]
Hello @johanna-rock 

I'd like to thank you for making the code and part of data public,  as @zjysteven  I'm also looking for the full dateset if applicable. 

Thanks, 
Ahmed

**Comment by johanna-rock** [comment]
Hi!

I uploaded the full data set with 2000, 250 and 250 samples for training, validation and testing. The readme is updated with the link to the full data set (https://nextcloud.spsc.tugraz.at/s/2qEEP6D2rHtFX64).

Best regards,
Johanna

**Comment by zjysteven** [comment]
@johanna-rock Thank you very much!

**Comment by Zhaeng14** [comment]
I am a student who is highly interested in your work on "Complex Signal Denoising and Interference Mitigation for Automotive Radar Using Convolutional Neural Networks." I came across your paper and noticed that you have open-sourced the code and dataset on GitHub. However, I have encountered difficulties in accessing the dataset.I am unable to open the website with the full dataset, and the website with a partial dataset shows that the file has expired

I would like to inquire whether it would be possible for you to share the dataset with me.

**Comment by SkyPoet** [comment]
@zjysteven Hi,  do you still keep the dataset of this repository? The original link can't be opened anymore.

**Comment by ahmedaelsharkawy** [comment]
Hi, 
I've a copy from this dataset you can use the link below to download it 
https://drive.google.com/drive/folders/1nKGUHpFMuLWAGvmhi1KnUo7qdUo38cyo?usp=sharing

**Comment by SkyPoet** [comment]
Hi,&nbsp;
I have successfully downloaded this dataset and really appreciate your help, thank you!
I've followed you on github as a token of appreciation.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "johanna-rock/imRICnn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月23日(星期一) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [johanna-rock/imRICnn] Is there a link to the full training dataset? (Issue #3)





 
Hi,
 I've a copy from this dataset you can use the link below to download it
 https://drive.google.com/drive/folders/1nKGUHpFMuLWAGvmhi1KnUo7qdUo38cyo?usp=sharing

**Comment by ahmedaelsharkawy** [comment]
@SkyPoet  you're welcome

**Comment by wumieya** [comment]
> 嗨，我有这个数据集的副本，您可以使用下面的链接下载它 https://drive.google.com/drive/folders/1nKGUHpFMuLWAGvmhi1KnUo7qdUo38cyo?usp=sharing

请问，这个数据集可以直接用于代码里进行训练和测试吗
